# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e36e977866b80ea528404fd68ce4afe2fe601e296ca9964ae544677f25129c3ea5ee8654924aa5826332b6176ebce026dd0833c3208d1b2bb720025a793f1f7

test:
  secret_key_base: ce401b81379a61f384d14e041fc269e5b46d3d50ffab16212bb886e3ddd2111c6c276cfff4fa5b2bbf4f04ca3dca905db2a2a059611ef818ae431853d9058672

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
